services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--import-realm", "--health-enabled=true" ]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  l.bank.accounts:
    image: ${DOCKER_REGISTRY-}lbankaccounts
    build:
      context: .
      dockerfile: src/L.Bank.Accounts/Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3