services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"

  l.bank.accounts:
    image: ${DOCKER_REGISTRY-}lbankaccounts
    build:
      context: .
      dockerfile: src/L.Bank.Accounts/Dockerfile
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Username=postgres;Password=postgres
      - ConnectionStrings__RabbitMQ=amqp://guest:guest@rabbitmq:5672 
    depends_on:
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_started
      postgres:
        condition: service_healthy
  
  postgres:
    image: postgres:17.5-alpine3.22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - postgresql-logs:/var/log/postgresql 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq:
    image: rabbitmq:4.1.3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgresql-data:
  postgresql-logs:
  rabbitmq-data:
  rabbitmq-logs: